[package]
name = "crates-io-changes-stream-server"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

[dependencies]
hyper = "*"
futures = "*"
crates-io-changes = { "path" = "../crates-io-changes", version = "*" }
serde = "1.0"
serde_json = "1.0"
